name: student_mobile
description: "Pragyu Student mobile application"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_secure_storage: ^11.1.1
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  livekit_client: ^2.13.0
  video_player: ^2.14.0
  chewie: ^1.17.1
  pdfrx: ^2.6.1
  path_provider: ^2.1.6
  image_picker: ^1.2.0
  crypto: ^3.0.6
  package_info_plus: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/env/
    - assets/images/
    - assets/images/brand/
    - assets/images/splash/
    - assets/images/onboarding/
    - assets/images/auth/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
